[target.aarch64-linux-android]
linker = "/home/atomofiron/Software/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++"

[target.armv7-linux-androideabi]
linker = "/home/atomofiron/Software/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang++"